version: '3.7'

services:
  db:
    image: mysql:8.0.29
    container_name: OeskDatabase
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "%"
    ports:
      - '3306:3306'
    volumes:
      - ./docker-files/db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  my-db:
